stages:
  - build

## defaults:
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SFOS_VERSION: 3.3.0.14
  TARGET: "armv7hl"
  SRCVER: 2020.09.20
  NEWSPEC: "yes"
  YAMLNAME: youtube-dl.yaml

cache:
  paths:
    - /var/cache/zypp/

.build:
  stage: build
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  script:
    - OUTDIR=~/output
    - BLDDIR=~/build
    - mkdir -p ${OUTDIR}
    - mkdir -p ${BLDDIR}
    - cp -a * ${BLDDIR}
    - pushd ${BLDDIR}
    - if [[ $NEWSPEC = "yes" ]]; then touch rpm/$YAMLNAME; fi
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare      | tee ${OUTDIR}/prepare.log
    - cat rpm/*.spec
    - cp -rv rpm/* ${OUTDIR}/
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET build -j 5   | tee ${OUTDIR}/build.log
    - mkdir -p $OUTDIR/$SFOS_VERSION
    - cp -rv RPMS/* ${OUTDIR}/$SFOS_VERSION
    - cp -rv rpm/* ${OUTDIR}
    - ls -lR ${OUTDIR}
  cache:
    paths:
      - /srv/mer/targets/SailfishOS-$SFOS_VERSION-$TARGET/var/cache/zypp/
  artifacts:
    paths:
      - "/home/nemo/output/*.yaml"
      - "/home/nemo/output/*.spec"
      - "/home/nemo/output/*.log"
      - "/home/nemo/output/$SFOS_VERSION/*.rpm"
    when: always


build-arm:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "armv7hl"

build-x86:
  when: manual
  extends: .build
  variables:
    TARGET: "i486"
