stages:
  - build

## defaults:
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SFOS_VERSION: 3.3.0.14
  TARGET: "armv7hl"
  SRCVER: 2020.09.20
  NEWSPEC: "yes"
  YAMLNAME: youtube-dl.yaml

cache:
  paths:
    - /var/cache/zypp/
    - "/home/.zypp-cache/"

.build:
  stage: build
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  script:
    # must be a child of $CI_PROJECT_DIR: https://stackoverflow.com/questions/47490688/gitlab-ci-artifacts-not-found#47491693
    - OUTDIR=$CI_PROJECT_DIR/output
    - BLDDIR=~/build
    - mkdir -p ${OUTDIR}
    - mkdir -p ${BLDDIR}
    - cp -a * ${BLDDIR}
    - pushd ${BLDDIR}
    - if [[ $NEWSPEC = "yes" ]]; then touch rpm/$YAMLNAME; fi
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare      | tee ${OUTDIR}/prepare.log
    - cat rpm/*.spec
    - cp -rv rpm/* ${OUTDIR}/
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET build --enable-debug   | tee ${OUTDIR}/build.log
    - mkdir -p $OUTDIR/$SFOS_VERSION
    - cp -rv RPMS/* ${OUTDIR}/$SFOS_VERSION
    - cp -rv rpm/* ${OUTDIR}
    - ls -lR ${OUTDIR}
  artifacts:
    paths:
      # must be a child of $CI_PROJECT_DIR: https://stackoverflow.com/questions/47490688/gitlab-ci-artifacts-not-found#47491693
      - output/*
    when: always


build-arm:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "armv7hl"

build-x86:
  when: manual
  extends: .build
  variables:
    TARGET: "i486"
